/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package evamichele.memorygame.frames;

/**
 *
 * @author Mpianatra
 */
public class HelpJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelpJFrame
     */
    public HelpJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHelpPanel = new javax.swing.JPanel();
        jHelpLabel = new javax.swing.JLabel();
        jObjectiveButton = new javax.swing.JButton();
        jOnePlayerButton = new javax.swing.JButton();
        jTwoPlayerButton = new javax.swing.JButton();
        jQuitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHelpPanel.setBackground(new java.awt.Color(204, 255, 255));

        jHelpLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jHelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHelpLabel.setText("Help Menu Option");

        jObjectiveButton.setText("Objective");
        jObjectiveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jOnePlayerButton.setText("One Player  Help");
        jOnePlayerButton.setToolTipText("");
        jOnePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnePlayerButtonActionPerformed(evt);
            }
        });

        jTwoPlayerButton.setText("Two Player Help");

        jQuitButton.setText("Quit");

        javax.swing.GroupLayout jHelpPanelLayout = new javax.swing.GroupLayout(jHelpPanel);
        jHelpPanel.setLayout(jHelpPanelLayout);
        jHelpPanelLayout.setHorizontalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jOnePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jObjectiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTwoPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jQuitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 82, Short.MAX_VALUE))
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jHelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jHelpPanelLayout.setVerticalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpLabel)
                .addGap(18, 18, 18)
                .addComponent(jObjectiveButton)
                .addGap(18, 18, 18)
                .addComponent(jOnePlayerButton)
                .addGap(18, 18, 18)
                .addComponent(jTwoPlayerButton)
                .addGap(18, 18, 18)
                .addComponent(jQuitButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jHelpLabel.getAccessibleContext().setAccessibleDescription("");
        jHelpLabel.getAccessibleContext().setAccessibleParent(jHelpLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jHelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOnePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOnePlayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOnePlayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHelpLabel;
    private javax.swing.JPanel jHelpPanel;
    private javax.swing.JButton jObjectiveButton;
    private javax.swing.JButton jOnePlayerButton;
    private javax.swing.JButton jQuitButton;
    private javax.swing.JButton jTwoPlayerButton;
    // End of variables declaration//GEN-END:variables
}
