/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package evamichele.memorygame.frames;

import evamichele.memorygame.control.HelpMenuControl;
import evamichele.memorygame.enums.HelpType;
import evamichele.memorygame.exceptions.MemorygameException;


/**
 *
 * @author Mpianatra
 */
public class HelpJFrame extends javax.swing.JFrame {
  HelpMenuControl helpCommands = new HelpMenuControl();
    

    /**
     * Creates new form HelpJFrame
     */
    
    public HelpJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
   
    public HelpMenuControl getHelpCommands() {
        return helpCommands;
    }


    
    private void displayHelpText(HelpType command) {
        try {
            String helpText = this.helpCommands.getHelpText(command);
            this.jTextArea1.setText(helpText);
        } catch (MemorygameException ex) {
            this.jTextArea1.setText(ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHelpPanel = new javax.swing.JPanel();
        jHelpLabel = new javax.swing.JLabel();
        jObjectiveButton = new javax.swing.JButton();
        jOnePlayerButton = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTwoPlayerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHelpPanel.setBackground(new java.awt.Color(204, 255, 255));

        jHelpLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jHelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHelpLabel.setText("Help Menu Option");

        jObjectiveButton.setText("Objective");
        jObjectiveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jObjectiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jObjectiveButtonMouseClicked(evt);
            }
        });

        jOnePlayerButton.setText("One Player  Help");
        jOnePlayerButton.setToolTipText("");
        jOnePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOnePlayerButtonMouseClicked(evt);
            }
        });

        jBexit.setText("Return");
        jBexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBexitMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusable(false);
        jTextArea1.setPreferredSize(new java.awt.Dimension(170, 100));
        jScrollPane1.setViewportView(jTextArea1);

        jTwoPlayerButton.setText("Two Player");
        jTwoPlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTwoPlayerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jHelpPanelLayout = new javax.swing.GroupLayout(jHelpPanel);
        jHelpPanel.setLayout(jHelpPanelLayout);
        jHelpPanelLayout.setHorizontalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jHelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jObjectiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jOnePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTwoPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jHelpPanelLayout.setVerticalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHelpPanelLayout.createSequentialGroup()
                        .addComponent(jObjectiveButton)
                        .addGap(18, 18, 18)
                        .addComponent(jOnePlayerButton)
                        .addGap(18, 18, 18)
                        .addComponent(jTwoPlayerButton)
                        .addGap(18, 18, 18)
                        .addComponent(jBexit)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jHelpLabel.getAccessibleContext().setAccessibleDescription("");
        jHelpLabel.getAccessibleContext().setAccessibleParent(jHelpLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jObjectiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jObjectiveButtonMouseClicked
        displayHelpText(HelpType.OBJECTIVE);
    }//GEN-LAST:event_jObjectiveButtonMouseClicked

    private void jOnePlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOnePlayerButtonMouseClicked
    displayHelpText(HelpType.ONE_PERSON_GAME);
    }//GEN-LAST:event_jOnePlayerButtonMouseClicked

    private void jTwoPlayerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTwoPlayerButtonMouseClicked
  displayHelpText(HelpType.TWO_PERSON_GAME);
    }//GEN-LAST:event_jTwoPlayerButtonMouseClicked

    private void jBexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBexitMouseClicked
  this.dispose();
    }//GEN-LAST:event_jBexitMouseClicked

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  /*      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpJFrame().setVisible(true);
            }
        });
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBexit;
    private javax.swing.JLabel jHelpLabel;
    private javax.swing.JPanel jHelpPanel;
    private javax.swing.JButton jObjectiveButton;
    private javax.swing.JButton jOnePlayerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jTwoPlayerButton;
    // End of variables declaration//GEN-END:variables
}
