/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package evamichele.memorygame.frames;

import evamichele.memorygame.views.HelpMenuView;

/**
 *
 * @author Mpianatra
 */
public class HelpJFrame extends javax.swing.JFrame {
    HelpMenuView helpMenuView = new HelpMenuView();
    

    /**
     * Creates new form HelpJFrame
     */
    
    public HelpJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHelpPanel = new javax.swing.JPanel();
        jHelpLabel = new javax.swing.JLabel();
        jObjectiveButton = new javax.swing.JButton();
        jOnePlayerButton = new javax.swing.JButton();
        jQuitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHelpPanel.setBackground(new java.awt.Color(204, 255, 255));

        jHelpLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jHelpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHelpLabel.setText("Help Menu Option");

        jObjectiveButton.setText("Objective");
        jObjectiveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jObjectiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jObjectiveButtonMouseClicked(evt);
            }
        });

        jOnePlayerButton.setText("One Player  Help");
        jOnePlayerButton.setToolTipText("");
        jOnePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnePlayerButtonActionPerformed(evt);
            }
        });

        jQuitButton.setText("Return");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jHelpPanelLayout = new javax.swing.GroupLayout(jHelpPanel);
        jHelpPanel.setLayout(jHelpPanelLayout);
        jHelpPanelLayout.setHorizontalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jHelpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jObjectiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOnePlayerButton)
                    .addComponent(jQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jHelpPanelLayout.setVerticalGroup(
            jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHelpPanelLayout.createSequentialGroup()
                        .addComponent(jObjectiveButton)
                        .addGap(18, 18, 18)
                        .addComponent(jOnePlayerButton)
                        .addGap(18, 18, 18)
                        .addComponent(jQuitButton)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jHelpLabel.getAccessibleContext().setAccessibleDescription("");
        jHelpLabel.getAccessibleContext().setAccessibleParent(jHelpLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOnePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOnePlayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOnePlayerButtonActionPerformed

    private void jObjectiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jObjectiveButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jObjectiveButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHelpLabel;
    private javax.swing.JPanel jHelpPanel;
    private javax.swing.JButton jObjectiveButton;
    private javax.swing.JButton jOnePlayerButton;
    private javax.swing.JButton jQuitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
